### ISSUE TITLE
Possible spelling error: "admeet"

### ISSUE THREAD

**Issue by simenheg** [standardebooks/arthur-conan-doyle_the-valley-of-fear#1]
Chapter 1-6, line 76:

> Man, I’ll admeet that I had my doubts if there was ever an outsider

I don't know whether it was intended to use the [Scots](https://en.wiktionary.org/wiki/admeet) spelling of the word, or whether it should be "admit"?

**Comment by acabal** [comment]
Can you check the page scans to see? A link is in the book colophon and content.opf file.

**Comment by simenheg** [comment]
> Can you check the page scans to see? A link is in the book colophon and content.opf file.

"Admeet" is also used in the page scans, so I guess it is intended.

**Comment by acabal** [comment]
OK, we'll leave it then. Thanks!
